version: "3"
services:
  mysql:
    image: "mysql:5.7"
    command: "--character-set-server='utf8mb4' --collation-server='utf8mb4_unicode_ci'"
    ports:
      - "33306:3306"
    logging:
      driver: local
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: spongebob
      MYSQL_PASSWORD: squarepants
      MYSQL_DATABASE: prisma_test
