name: Branch Push

on: [push]

jobs:
  test:
    name: Test
    timeout-minutes: 20
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up services
        run: docker-compose -p dev -f docker-compose.yml up -d
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: npm ci
      - name: Migrate
        run: npm run test-migrate
      - name: Test
        run: npm run test
        env:
          FORCE_COLOR: "true"
